# Convert original PNGs to native LVGL RGB565 + alpha without scaling.
# Run when artwork changes. Firmware builds use the generated C resource.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$projectRoot = Split-Path $PSScriptRoot -Parent
$appRoot = Join-Path $projectRoot 'src/app/app_05'
$outputPath = Join-Path $appRoot 'asset/pc_monitor_images.c'
$code = [System.Text.StringBuilder]::new()
[void]$code.AppendLine('// Generated by tools/embed_pc_monitor_assets.ps1. Do not edit pixel data.')
[void]$code.AppendLine('#include "ui.h"')
[void]$code.AppendLine('#if LV_COLOR_DEPTH != 16 || LV_COLOR_16_SWAP != 0')
[void]$code.AppendLine('#error "PC Monitor assets require RGB565, LV_COLOR_16_SWAP=0"')
[void]$code.AppendLine('#endif')
foreach ($asset in @(
    @{ File='pc_monitor_bg.png'; Symbol='pc_monitor_background'; Width=320; Height=240 },
    @{ File='pc_monitor_ui_X10,Y2.png'; Symbol='pc_monitor_overlay'; Width=302; Height=230 }
)) {
    $bitmap = [System.Drawing.Bitmap]::new((Join-Path $appRoot $asset.File))
    try {
        if ($bitmap.Width -ne $asset.Width -or $bitmap.Height -ne $asset.Height) {
            throw "Unexpected dimensions for $($asset.File)"
        }
        [void]$code.AppendLine("static const LV_ATTRIBUTE_MEM_ALIGN uint8_t $($asset.Symbol)_data[] = {")
        for ($y = 0; $y -lt $bitmap.Height; $y++) {
            for ($x = 0; $x -lt $bitmap.Width; $x++) {
                $pixel = $bitmap.GetPixel($x, $y)
                $rgb = (([int]$pixel.R -shr 3) -shl 11) -bor (([int]$pixel.G -shr 2) -shl 5) -bor ([int]$pixel.B -shr 3)
                [void]$code.AppendFormat('0x{0:X2},0x{1:X2},0x{2:X2},', ($rgb -band 255), ($rgb -shr 8), $pixel.A)
                if (($x % 8) -eq 7) { [void]$code.AppendLine() }
            }
            [void]$code.AppendLine()
        }
        [void]$code.AppendLine('};')
        [void]$code.AppendLine("const lv_img_dsc_t $($asset.Symbol) = {")
        [void]$code.AppendLine("    .header = { .cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .w = $($bitmap.Width), .h = $($bitmap.Height) },")
        [void]$code.AppendLine("    .data_size = sizeof($($asset.Symbol)_data), .data = $($asset.Symbol)_data")
        [void]$code.AppendLine('};')
    } finally { $bitmap.Dispose() }
}
[System.IO.File]::WriteAllText($outputPath, $code.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $outputPath (original alpha preserved; no scaling)."
